apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: aksstore
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000