apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: aksstore
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002